# Generated by Django 5.0.4 on 2024-04-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('emailUsuario', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Email')),
                ('nombreUsuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('contraseñaUsuario', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
